language: node_js
node_js:
  - '12'
cache:
  directories:
    - node_modules
stages:
  - test
  - build
    if: branch = master
install:
  - npm i
jobs:
  include:
    - stage: test
      script: npm run test
    - stage: build
      script: npm run build

