version: '3'

services:
  frederikaulich.com:
    build: '.'
    image: frederikaulich-fe
    container_name: frederikaulich.com
    restart: always
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=www.frederikaulich.com,frederikaulich.com
      - VIRTUAL_PORT=3001
      - LETSENCRYPT_HOST=www.frederikaulich.com,frederikaulich.com
